# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

#

name: PySys tests

on:
  push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      # disable fail fast since it's useful to see test results for all platforms even if some failed
      fail-fast: false
      matrix:
        include:
          - test-run-id: ubuntu
            os: ubuntu-latest
            
          - test-run-id: macos
            os: macos-latest
            
          - test-run-id: win
            os: windows-latest
            
    runs-on: ${{matrix.os}}
    
    steps:
      # Setup the desired version of Python and PySys
      - uses: actions/checkout@v2
      - name: Set up the version of Python you want to use with PySys
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        id: deps
        run: |
          python -m pip install --upgrade pip wheel
          pip install coverage==4.5.4 codecov pysys==1.5.1
          
      - name: Test with PySys
        working-directory: test
        shell: bash
        id: pysys
        env:
          PYSYS_DEFAULT_THREADS_PER_CPU: 1.5
        run: |
          python -m pysys run --threads=auto --purge --record --mode=ALL -XpythonCoverage --outdir ${GITHUB_WORKSPACE}/test/pysys-output/${{matrix.test-run-id}}
        
        # If any tests fail, PySys will return an error code and subsequent steps won't execute unless they have an if: always()

      - name: Temp debugging
        if: always() && contains(steps.pysys.outputs, 'pysys-performance-artifacts')
        shell: bash
        run: |
          echo path is: ${GITHUB_WORKSPACE}/test/pysys-output
          echo steps: ${{ toJson(steps) }}
          echo step outputs: ${{ toJson(steps.pysys.outputs) }}
          echo artifacts: ${{ steps.pysys.outputs.pysys-performance-artifacts }}


      - name: Temp debugging cmp to empty string
        if: always() && steps.pysys.outputs.pysys-performance-artifacts == ''
        shell: bash
        run: |
          echo step outputs: ${{ toJson(steps.pysys.outputs) }}

      - name: Temp debugging cmp to null
        if: always() && steps.pysys.outputs.pysys-performance-artifacts == null
        shell: bash
        run: |
          echo step outputs: ${{ toJson(steps.pysys.outputs) }}

      - name: Temp debugging2
        if: always() && steps.pysys.outputs.pysys-performance-artifacts != false
        shell: bash
        run: |
          echo step outputs: ${{ toJson(steps.pysys.outputs) }}


      - name: Temp debugging - true
        if: true
        shell: bash
        run: |
          echo step outputs: ${{ toJson(steps.pysys.outputs) }}

      - name: Temp debugging print it
        if: always()
        shell: bash
        run: |
          echo artifacts: ${{ steps.pysys.outputs.pysys-performance-artifacts }}


      - name: Upload performance artifacts
        uses: actions/upload-artifact@v2
        if: always()

        with:
          name: pysys-performance-${{matrix.test-run-id}}
          path: ${{ steps.pysys.outputs.pysys-performance-artifacts }}
          #path: test/performance_output/

      - name: Upload test failure artifacts
        uses: actions/upload-artifact@v2
        if: failure()

        with:
          name: pysys-output-${{matrix.test-run-id}}
          path: test/pysys-output/${{matrix.test-run-id}}/*
