# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PySys sample project

on:
  push:
  #:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up the version of Python you want to use with PySys
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage==4.5.4 codecov pysys==1.5.1
    - name: Test with PySys
      run: |
        cd test
        pysys.py run --threads=auto --purge --record --mode=ALL -XpythonCoverage
    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: pysys.log
        # A file, directory or wildcard pattern that describes what to upload
        path: test/pysys-junit-report/TEST-MyApp_cor_001.xml
