# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

#

name: PySys tests

on:
  push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      # disable fail fast since it's useful to see test results for all platforms even if some failed
      fail-fast: false
      matrix:
        include:
          - test-run-id: ubuntu
            os: ubuntu-latest
            
          - test-run-id: macos
            os: macos-latest
            
          - test-run-id: win
            os: windows-latest
            
    runs-on: ${{matrix.os}}
    
    steps:
      # Setup the desired version of Python and PySys
      - uses: actions/checkout@v2
      - name: Set up the version of Python you want to use with PySys
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        id: deps
        run: |
		  # is wheel needed?
          python -m pip install --upgrade pip
          pip install coverage
          # codecov 
          pip install pysys==1.5.1
          
      - name: Test with PySys
        working-directory: test
        shell: bash
        id: pysys
        env:
          PYSYS_DEFAULT_THREADS_PER_CPU: 1.5
        run: |
          python -m pysys run --threads=auto --purge --record --mode=ALL -XpythonCoverage --outdir ${GITHUB_WORKSPACE}/test/__pysys_output/${{matrix.test-run-id}}
        
        # If any tests fail, PySys will return an error code and subsequent steps won't execute unless they have an if: always()

      - name: Upload code coverage (Python)
        uses: codecov/codecov-action@v1
        if: always()
        with:
          file: test/__pysys_python_coverage_${{matrix.test-run-id}}/*
          flags: unittests # optional
      
      - name: Upload coverage debugging artifact
        uses: actions/upload-artifact@v2
        if: always()

        with:
          name: pysys-coverage-${{matrix.test-run-id}}
          path: test/__pysys_python_coverage_${{matrix.test-run-id}}/

      - name: Upload performance artifacts
        uses: actions/upload-artifact@v2
        # To avoid warnings, only do this if some performance results were generated
        if: always() && steps.pysys.outputs.pysys-performance-artifacts != null

        with:
          name: pysys-performance-${{matrix.test-run-id}}
          path: ${{ steps.pysys.outputs.pysys-performance-artifacts }}

      - name: Upload test failure artifacts
        uses: actions/upload-artifact@v2
        if: failure()

        with:
          name: pysys_output_${{matrix.test-run-id}}
          path: test/__pysys_output/${{matrix.test-run-id}}
