# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

#

name: PySys tests

on:
  push:
  #  branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      # disable fail fast since it's useful to see test results for all platforms even if some failed
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{matrix.os}}
    
    steps:
      # Setup the desired version of Python and PySys
      - uses: actions/checkout@v2
      - name: Set up the version of Python you want to use with PySys
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install coverage==4.5.4 codecov pysys==1.5.1
          
      - name: Test with PySys
        working-directory: test
        env:
          PYSYS_DEFAULT_THREADS_PER_CPU: 1.5
        run: |
          python -m pysys run --threads=auto --purge --record --mode=ALL -XpythonCoverage

        # If any tests fail, PySys will return an error code and subsequent steps won't execute unless they have an if: ${{always()}}

      - name: Upload logs
        uses: actions/upload-artifact@v2
        if: ${{ always() }}

        with:
          # Artifact name
          name: pysys-junit-${{matrix.os}}
          # A file, directory or wildcard pattern that describes what to upload
          path: test/pysys-junit-report
          #/TEST-MyApp_cor_001.xml
